ALTER TABLE events ADD COLUMN IF NOT EXISTS user_id TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS user_email TEXT;

ALTER TABLE issues ADD COLUMN IF NOT EXISTS last_user_id TEXT;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS last_user_email TEXT;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS github_issue_url TEXT;
